export const AUDIT_ACTIONS = {
  USER_LOGIN: "USER_LOGIN",
  INVOICE_CREATED: "INVOICE_CREATED",
  INVOICE_SUBMITTED_FOR_APPROVAL: "INVOICE_SUBMITTED_FOR_APPROVAL",
  INVOICE_APPROVED: "INVOICE_APPROVED",
  INVOICE_REJECTED: "INVOICE_REJECTED",
  INVOICE_SUBMITTED_TO_PAYER: "INVOICE_SUBMITTED_TO_PAYER",
  CLAIM_GENERATED: "CLAIM_GENERATED",
  PAYMENT_RECEIVED: "PAYMENT_RECEIVED",
  PAYMENT_ALLOCATED: "PAYMENT_ALLOCATED",
  RECEIPT_GENERATED: "RECEIPT_GENERATED",
  INVOICE_CANCELLED: "INVOICE_CANCELLED",
  INVOICE_REVERSED: "INVOICE_REVERSED",
  USER_ROLE_CHANGED: "USER_ROLE_CHANGED",
  BRANCH_ASSIGNMENT_CHANGED: "BRANCH_ASSIGNMENT_CHANGED",
  DEPARTMENT_ASSIGNMENT_CHANGED: "DEPARTMENT_ASSIGNMENT_CHANGED"
};
