export const mockProviders = [
  {
    id: "PRV-001",
    accountNumber: "ACC-2024-0001",
    providerName: "Jubilee Health Insurance",
    providerType: "Insurance",
    registrationNumber: "IRA/2005/0034",
    contactPerson: "Grace Wanjiru",
    phone: "0722 100 200",
    email: "claims@jubileehealth.co.ke",
    address: "Jubilee Insurance House, Wabera St, Nairobi",
    creditLimit: 500000,
    creditPeriod: 90,
    outstandingBalance: 128450,
    status: "Active",
    accountOpenDate: "2024-01-15",
    schemes: ["SCH-001", "SCH-002"],
  },
  {
    id: "PRV-002",
    accountNumber: "ACC-2024-0002",
    providerName: "AAR Healthcare",
    providerType: "Insurance",
    registrationNumber: "IRA/2003/0012",
    contactPerson: "Martin Otieno",
    phone: "0733 200 300",
    email: "providers@aar.co.ke",
    address: "AAR House, Upper Hill, Nairobi",
    creditLimit: 750000,
    creditPeriod: 60,
    outstandingBalance: 312000,
    status: "Active",
    accountOpenDate: "2024-02-01",
    schemes: ["SCH-003"],
  },
  {
    id: "PRV-003",
    accountNumber: "ACC-2024-0003",
    providerName: "Kenya Airways Staff Union",
    providerType: "Corporate",
    registrationNumber: "KAQ/HR/2010/089",
    contactPerson: "Alice Kamau",
    phone: "0711 300 400",
    email: "welfare@kenyaairways.com",
    address: "JKIA Terminal 2, Nairobi",
    creditLimit: 200000,
    creditPeriod: 30,
    outstandingBalance: 54000,
    status: "Active",
    accountOpenDate: "2024-03-10",
    schemes: ["SCH-004"],
  },
  {
    id: "PRV-004",
    accountNumber: "ACC-2024-0004",
    providerName: "Safaricom PLC",
    providerType: "Corporate",
    registrationNumber: "CPY/2000/0456",
    contactPerson: "James Mwangi",
    phone: "0722 400 500",
    email: "medical@safaricom.co.ke",
    address: "Safaricom House, Westlands, Nairobi",
    creditLimit: 1000000,
    creditPeriod: 45,
    outstandingBalance: 0,
    status: "Suspended",
    accountOpenDate: "2023-11-05",
    schemes: [],
  },
  {
    id: "PRV-005",
    accountNumber: "ACC-2024-0005",
    providerName: "Ministry of Health",
    providerType: "Government",
    registrationNumber: "GOK/MOH/2015/001",
    contactPerson: "Dr. Peter Kiptoo",
    phone: "0800 723 577",
    email: "finance@health.go.ke",
    address: "Afya House, Cathedral Road, Nairobi",
    creditLimit: 2000000,
    creditPeriod: 90,
    outstandingBalance: 890000,
    status: "Active",
    accountOpenDate: "2023-06-20",
    schemes: ["SCH-005"],
  },
];

export const SERVICE_POINTS = [
  "Consultation (OPD)",
  "Pharmacy",
  "Laboratory",
  "Radiology / Imaging",
  "Physiotherapy",
  "Dental",
  "Optical",
  "Casualty / Emergency",
  "Procedures / Theatre",
  "Maternity",
  "Inpatient (IPD)",
];

export const mockSchemes = [
  {
    id: "SCH-001",
    schemeName: "Jubilee Gold Plan",
    providerId: "PRV-001",
    providerName: "Jubilee Health Insurance",
    biometricType: "Smart",
    copaymentType: "Fixed",
    copaymentScope: "Per Service Point",
    categories: [
      { name: "Principal Member", copayAmount: 300 },
      { name: "Spouse", copayAmount: 300 },
      { name: "Child", copayAmount: 150 },
    ],
    servicePoints: [
      { point: "Consultation (OPD)", copayOverride: null, limit: 80000, guidelines: "Referral letter required for specialist visits." },
      { point: "Pharmacy", copayOverride: null, limit: 40000, guidelines: "Generics preferred. Brand drugs require prior authorization." },
      { point: "Laboratory", copayOverride: null, limit: 30000, guidelines: "Lab requests must be from attending physician." },
      { point: "Radiology / Imaging", copayOverride: 500, limit: 20000, guidelines: "X-ray and ultrasound covered. MRI requires pre-authorization." },
      { point: "Inpatient (IPD)", copayOverride: 1000, limit: 200000, guidelines: "Admission must be pre-authorized within 24 hours." },
    ],
    overallLimit: 500000,
    hasOverallLimit: true,
    hasServicePointLimits: true,
    status: "Active",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    notes: "Excludes cosmetic procedures and pre-existing conditions in the first year.",
  },
  {
    id: "SCH-002",
    schemeName: "Jubilee Silver Plan",
    providerId: "PRV-001",
    providerName: "Jubilee Health Insurance",
    biometricType: "Slade",
    copaymentType: "Percentage",
    copaymentScope: "On Consultation",
    categories: [
      { name: "Principal Member", copayPercent: 20 },
      { name: "Spouse", copayPercent: 20 },
      { name: "Child", copayPercent: 10 },
    ],
    servicePoints: [
      { point: "Consultation (OPD)", copayOverride: null, limit: null, guidelines: "20% copay applies on consultation fee only." },
      { point: "Pharmacy", copayOverride: null, limit: 20000, guidelines: "Generic drugs only covered." },
    ],
    overallLimit: 200000,
    hasOverallLimit: true,
    hasServicePointLimits: false,
    status: "Active",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    notes: "Copayment applies on consultation fee only. Pharmacy covered at 100% up to limit.",
  },
  {
    id: "SCH-003",
    schemeName: "AAR Executive Cover",
    providerId: "PRV-002",
    providerName: "AAR Healthcare",
    biometricType: "Mtiba",
    copaymentType: "None",
    copaymentScope: "N/A",
    categories: [
      { name: "Executive", copayAmount: 0 },
      { name: "Dependent", copayAmount: 0 },
    ],
    servicePoints: [
      { point: "Consultation (OPD)", copayOverride: null, limit: null, guidelines: "No copayment. Cashless service." },
      { point: "Pharmacy", copayOverride: null, limit: null, guidelines: "Full cover. Formulary list applies." },
      { point: "Laboratory", copayOverride: null, limit: null, guidelines: "All diagnostics covered." },
      { point: "Radiology / Imaging", copayOverride: null, limit: null, guidelines: "All modalities covered." },
    ],
    overallLimit: null,
    hasOverallLimit: false,
    hasServicePointLimits: false,
    status: "Active",
    effectiveDate: "2024-01-01",
    expiryDate: "2025-12-31",
    notes: "Full cashless cover. No copayment for executive members.",
  },
  {
    id: "SCH-004",
    schemeName: "KQ Staff Medical Scheme",
    providerId: "PRV-003",
    providerName: "Kenya Airways Staff Union",
    biometricType: "SHA",
    copaymentType: "Fixed",
    copaymentScope: "Per Service Point",
    categories: [
      { name: "Staff", copayAmount: 200 },
      { name: "Spouse", copayAmount: 200 },
      { name: "Child (Under 18)", copayAmount: 100 },
    ],
    servicePoints: [
      { point: "Consultation (OPD)", copayOverride: null, limit: 50000, guidelines: "Present staff ID and medical card." },
      { point: "Pharmacy", copayOverride: null, limit: 30000, guidelines: "Prescribed medicines only." },
      { point: "Dental", copayOverride: 500, limit: 15000, guidelines: "Preventive and restorative only. Orthodontics excluded." },
    ],
    overallLimit: 150000,
    hasOverallLimit: true,
    hasServicePointLimits: true,
    status: "Active",
    effectiveDate: "2024-03-01",
    expiryDate: "2025-02-28",
    notes: "Annual renewal. Staff must revalidate membership each financial year.",
  },
  {
    id: "SCH-005",
    schemeName: "MOH Civil Servants Scheme",
    providerId: "PRV-005",
    providerName: "Ministry of Health",
    biometricType: "SHA",
    copaymentType: "None",
    copaymentScope: "N/A",
    categories: [
      { name: "Civil Servant", copayAmount: 0 },
      { name: "Spouse", copayAmount: 0 },
      { name: "Child", copayAmount: 0 },
    ],
    servicePoints: [
      { point: "Consultation (OPD)", copayOverride: null, limit: null, guidelines: "Valid national ID and appointment letter required." },
      { point: "Pharmacy", copayOverride: null, limit: null, guidelines: "KEML formulary applies." },
      { point: "Laboratory", copayOverride: null, limit: null, guidelines: "Standard diagnostic tests covered." },
      { point: "Inpatient (IPD)", copayOverride: null, limit: null, guidelines: "General ward cover. Pre-authorization required." },
    ],
    overallLimit: null,
    hasOverallLimit: false,
    hasServicePointLimits: false,
    status: "Active",
    effectiveDate: "2024-01-01",
    expiryDate: "2024-12-31",
    notes: "Covers civil servants under NHIF Civil Servants Scheme framework.",
  },
];
