export const ROLES = {
  SUPER_ADMIN: "SUPER_ADMIN",
  HOSPITAL_ADMIN: "HOSPITAL_ADMIN",
  BRANCH_ADMIN: "BRANCH_ADMIN",
  BILLING_OFFICER: "BILLING_OFFICER",
  CREDIT_CONTROLLER: "CREDIT_CONTROLLER",
  ACCOUNTANT: "ACCOUNTANT",
  CLAIMS_OFFICER: "CLAIMS_OFFICER",
  DOCTOR: "DOCTOR",
  RECEPTIONIST: "RECEPTIONIST",
  AUDITOR: "AUDITOR"
};

export const PERMISSIONS = {
  VIEW_INVOICES: "VIEW_INVOICES",
  CREATE_INVOICES: "CREATE_INVOICES",
  EDIT_DRAFT_INVOICES: "EDIT_DRAFT_INVOICES",
  APPROVE_INVOICES: "APPROVE_INVOICES",
  SUBMIT_TO_PAYER: "SUBMIT_TO_PAYER",
  GENERATE_CLAIMS: "GENERATE_CLAIMS",
  RECEIVE_PAYMENTS: "RECEIVE_PAYMENTS",
  REVERSE_INVOICES: "REVERSE_INVOICES",
  VIEW_REPORTS: "VIEW_REPORTS",
  MANAGE_USERS: "MANAGE_USERS",
  MANAGE_BRANCHES: "MANAGE_BRANCHES",
  MANAGE_TENANTS: "MANAGE_TENANTS"
};

export const DEFAULT_ROLE_PERMISSIONS = {
  [ROLES.SUPER_ADMIN]: Object.values(PERMISSIONS),
  [ROLES.HOSPITAL_ADMIN]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.EDIT_DRAFT_INVOICES,
    PERMISSIONS.APPROVE_INVOICES,
    PERMISSIONS.SUBMIT_TO_PAYER,
    PERMISSIONS.GENERATE_CLAIMS,
    PERMISSIONS.RECEIVE_PAYMENTS,
    PERMISSIONS.REVERSE_INVOICES,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS,
    PERMISSIONS.MANAGE_BRANCHES
  ],
  [ROLES.BRANCH_ADMIN]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.EDIT_DRAFT_INVOICES,
    PERMISSIONS.APPROVE_INVOICES,
    PERMISSIONS.SUBMIT_TO_PAYER,
    PERMISSIONS.GENERATE_CLAIMS,
    PERMISSIONS.RECEIVE_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS,
    PERMISSIONS.MANAGE_USERS
  ],
  [ROLES.BILLING_OFFICER]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.CREATE_INVOICES,
    PERMISSIONS.EDIT_DRAFT_INVOICES
  ],
  [ROLES.CREDIT_CONTROLLER]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.APPROVE_INVOICES,
    PERMISSIONS.SUBMIT_TO_PAYER,
    PERMISSIONS.VIEW_REPORTS
  ],
  [ROLES.ACCOUNTANT]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.RECEIVE_PAYMENTS,
    PERMISSIONS.VIEW_REPORTS
  ],
  [ROLES.CLAIMS_OFFICER]: [
    PERMISSIONS.VIEW_INVOICES,
    PERMISSIONS.GENERATE_CLAIMS,
    PERMISSIONS.SUBMIT_TO_PAYER
  ],
  [ROLES.DOCTOR]: [PERMISSIONS.VIEW_INVOICES],
  [ROLES.RECEPTIONIST]: [PERMISSIONS.VIEW_INVOICES, PERMISSIONS.CREATE_INVOICES],
  [ROLES.AUDITOR]: [PERMISSIONS.VIEW_INVOICES, PERMISSIONS.VIEW_REPORTS]
};
